### ISSUE TITLE
dependencies: gulp-minify-css deprecation

### ISSUE THREAD

**Issue by scniro** [bquarks/polygulp#9]
[gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css) has been in deprecated in favor of [gulp-clean-css](https://github.com/scniro/gulp-clean-css). Please open an [issue](https://github.com/scniro/gulp-clean-css/issues) with the new repository if you do upgrade and experience any unexpected behavior. I look forward to maintaining this package moving forward.

**Comment by ivanrod** [comment]
Thanks for report! [gulp-clean-css](https://github.com/scniro/gulp-clean-css) has been included in Polygulp and will be available in the next release. 9a9d53570cdacf401b4ae905b23cc3b485f8960e
